### ISSUE TITLE
Add to the terraform blog post how the user is supposed to interact from his locale machine with the remote daemon

### ISSUE THREAD

**Issue by tiero** [tdex-network/dev-portal#19]

**Comment by kcoax** [comment]
So I added part of the text explaining how to do it, but few things to overcome: 
- When installing tdex, should we clone tdex-deamon repo or should we add tdex cli to tdex-box too. 
- What about rest of the commands, interaction with markets etc, are those required? 
- Once tls and macaroons are configured in tdex config, is there any other authentication step left? 

Regarding SCP of the files, I was wondering if someone is using Linux its going to be easy, with rsync, but what about windows and other stuff?

**Comment by tiero** [comment]
> When installing tdex, should we clone tdex-deamon repo or should we add tdex cli to tdex-box too.

No, we should let the user download the binary already built from github releases for his own OS, either `tdex-v0.5.3-darwin-amd64` or `tdex-v0.5.3-linux-amd64`. Thast the installer bash script I mentioned we should maybe add to scripts here 

> What about rest of the commands, interaction with markets etc, are those required?

Once `tdex` CLI is configured locally and can reach the remote machine with `tdexd` I think we can link to the docs about liquidity provider

> Once tls and macaroons are configured in tdex config, is there any other authentication step left?

no

> but what about windows and other stuff?

I think we should only cover unix systems, so either linux or macos, where AFAIK scp works

**Comment by tiero** [comment]
- [] add Onion Hidden Service container for trade interface in the terraform/compose
- [] add documentation for getting onion endpoint after deployment is done
- [] link to tdex registry in dev portal page to register the onion endpoint printed in terminal
- [] add tdex cli installer bash script for the local machine and document how to pull down macaroon and tls self signed certificate 
- [] document how to configure the cli and make a test command like ie. `tdex listmarket`, then link to dev portal pages
