### ISSUE TITLE
Implement versioning

### ISSUE THREAD

**Issue by Janaka-Steph** [TDex-network/dev-portal#5]
https://docusaurus.io/docs/versioning
Doc says: "Versioning is best suited for websites with high-traffic and rapid changes to documentation between versions. If your documentation rarely changes, don't add versioning to your documentation."
What do you think?

**Comment by tiero** [comment]
don't think we are that point tdex related, we are almost stable API wise (on daemon, specs and SDKs) so would not see any benefit having this.
