### ISSUE TITLE
Replace homepage images with more appropriate ones

### ISSUE THREAD

**Issue by Janaka-Steph** [TDex-network/dev-portal#7]

**Comment by tiero** [comment]
You can check here https://undraw.co/

**Comment by tiero** [comment]
https://pixabay.com/ https://undraw.co/ 
https://undraw.co/
https://isometric.online/ 
https://www.glazestock.com/ 
https://lukaszadam.com 
https://woobro.design https://www.opendoodles.com https://wweb.dev/resources/free-svg-illustrations 
https://illlustrations.co/
https://www.freepik.com
https://blush.design/

https://www.humaaans.com/
https://www.drawkit.io/
https://joeschmoe.io/
https://flowlava.club/ 
https://www.autodraw.com/ - Automatic Drawing
